version: 0.0.0.{build}
image: Visual Studio 2015


environment:
  QTDIR: C:\Qt\5.9.2\msvc2015
  VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  TOOLSDIR: C:\Qt\Tools\QtCreator
  INNOSETUPPATH: C:\Program Files (x86)\Inno Setup 5\
  INSTALLER_NAME: "%APPVEYOR_PROJECT_NAME%%APPVEYOR_BUILD_VERSION%"
  PR_NAME: "%APPVEYOR_PROJECT_NAME%"
  BUILD_V: "%APPVEYOR_BUILD_VERSION%"
  BUILD_F: "%APPVEYOR_BUILD_FOLDER%"

before_build:
  - set PATH=%PATH%;%QTDIR%\bin;%VSPATH%\bin;%TOOLSDIR%\bin;%INNOSETUPPATH%
  - call "%VSPATH%\vcvarsall.bat"
  - mkdir build

build_script:
  - cd build
  - qmake ../tputt.pro -spec win32-msvc
  - jom

after_build:
  - windeployqt --release %APPVEYOR_BUILD_FOLDER%\bin\release --qmldir %APPVEYOR_BUILD_FOLDER%
  - xcopy C:\OpenSSL-Win32\bin\libeay32.dll %APPVEYOR_BUILD_FOLDER%\bin\release /y
  - xcopy C:\OpenSSL-Win32\bin\ssleay32.dll %APPVEYOR_BUILD_FOLDER%\bin\release /y
  - iscc.exe /Qp /DAPPVEYOR_PROJECT_NAME=%PR_NAME% /DAPPVEYOR_BUILD_VERSION=%BUILD_V% /DINSTALLER_NAME=%INSTALLER_NAME% /DAPPVEYOR_BUILD_FOLDER=%BUILD_F% "%APPVEYOR_BUILD_FOLDER%\.appveyor\installer.iss"
  - 7z a -y ..\bin\installs\tttpu.zip %APPVEYOR_BUILD_FOLDER%\bin\release\*

artifacts:
  - path: bin/installs/tttpu.zip
    name: archive
    type: zip
  - path: bin/installs/%INSTALLER_NAME%.exe
    name: installer

deploy:
  tag: $(appveyor_repo_tag_name) 
  release: $(appveyor_project_name)-v$(appveyor_build_version)
  description: 'Auto release on tag $(appveyor_repo_tag_name)' 
  provider: GitHub
  artifact: installer
  prerelease: true
  auth_token:
    secure: +I1mbAzf5mFFmAHuGk/fgqd2RWhOQZzen5MRGXYyqZ+dFi5Px2JsPOj/4BGQ4Wl8
  on:
    appveyor_repo_tag: true

deploy:
  release: $(appveyor_project_name)-v$(appveyor_build_version)
  description: 'Auto release'
  provider: GitHub
  artifact: installer
  prerelease: false
  draft: false
  auth_token:
    secure: +I1mbAzf5mFFmAHuGk/fgqd2RWhOQZzen5MRGXYyqZ+dFi5Px2JsPOj/4BGQ4Wl8
  on:
    master: true 
